version: '3'
services:
  rasa_fr:
    image: rasa_test
    build:
      context: .
    environment:
      - REDIS_HOST=redis
    volumes:
      - $PWD:/app
    ports:
      - "5005:5005"
    command: python bot.py --port 5005
  rasa_en:
    image: rasa_test
    build:
      context: .
    volumes:
      - $PWD:/app
    ports:
      - "5006:5006"
    command: python bot.py --port 5006
  redis:  
    image: redis
    build:
      context: ./redis
    volumes:
      - ${PWD}/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command : [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

